#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-rstudio
Version  : 1.2.1335
Release  : 2
URL      : https://github.com/rstudio/rstudio/archive/v1.2.1335.tar.gz
Source0  : https://github.com/rstudio/rstudio/archive/v1.2.1335.tar.gz
Source1  : https://s3.amazonaws.com/rstudio-buildtools/gin-2.1.2.zip
Source2  : https://s3.amazonaws.com/rstudio-buildtools/gwt-2.8.1.zip
Source3  : https://s3.amazonaws.com/rstudio-buildtools/junit-4.9b3.jar
Source4  : https://s3.amazonaws.com/rstudio-buildtools/mathjax-26.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause GPL-3.0 LGPL-2.1 MIT MPL-1.1
Requires: R-rstudio-bin = %{version}-%{release}
Requires: R-rstudio-data = %{version}-%{release}
Requires: R-rstudio-license = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : R
BuildRequires : R-dev
BuildRequires : R-lib
BuildRequires : apache-ant
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : openjdk
BuildRequires : openssl-dev
BuildRequires : pandoc
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5OpenGL)
BuildRequires : pkgconfig(Qt5Positioning)
BuildRequires : pkgconfig(Qt5PrintSupport)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickWidgets)
BuildRequires : pkgconfig(Qt5Sensors)
BuildRequires : pkgconfig(Qt5Sql)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5WebChannel)
BuildRequires : pkgconfig(Qt5WebEngine)
BuildRequires : pkgconfig(Qt5WebEngineWidgets)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5Xml)
BuildRequires : pkgconfig(Qt5XmlPatterns)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(uuid)
BuildRequires : zlib-dev
Patch1: 0001-Disable-installation-of-pandoc.patch

%description
/*
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

%package bin
Summary: bin components for the R-rstudio package.
Group: Binaries
Requires: R-rstudio-data = %{version}-%{release}
Requires: R-rstudio-license = %{version}-%{release}

%description bin
bin components for the R-rstudio package.


%package data
Summary: data components for the R-rstudio package.
Group: Data

%description data
data components for the R-rstudio package.


%package license
Summary: license components for the R-rstudio package.
Group: Default

%description license
license components for the R-rstudio package.


%prep
%setup -q -n rstudio-1.2.1335
cd ..
%setup -q -T -D -n rstudio-1.2.1335 -b 4
cd ..
%setup -q -T -D -n rstudio-1.2.1335 -b 2
cd ..
%setup -q -T -D -n rstudio-1.2.1335 -b 1
cd ..
%setup -q -T -D -n rstudio-1.2.1335 -b 3
mkdir -p dependencies/common/mathjax-26
cp -r %{_topdir}/BUILD/mathjax-26/* %{_topdir}/BUILD/rstudio-1.2.1335/dependencies/common/mathjax-26
mkdir -p src/gwt/lib/gwt/2.8.1
cp -r %{_topdir}/BUILD/gwt-2.8.1/* %{_topdir}/BUILD/rstudio-1.2.1335/src/gwt/lib/gwt/2.8.1
%patch1 -p1

%build
## build_prepend content
export LD_LIBRARY_PATH=/usr/lib64/R/lib/
mkdir dependencies/common/dictionaries
cp %{SOURCE3} src/gwt/lib
GIN_BASENAME=`basename %{SOURCE1} .zip`
mkdir -p src/gwt/lib/${GIN_BASENAME/-//}
unzip -q -d src/gwt/lib/${GIN_BASENAME/-//} %{SOURCE1}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559343883
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DQT_QMAKE_EXECUTABLE=`which qmake` \
-DCMAKE_INSTALL_PREFIX=/usr/lib64/R/rstudio
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1559343883
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-rstudio
cp COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/COPYING
cp NOTICE %{buildroot}/usr/share/package-licenses/R-rstudio/NOTICE
cp dependencies/common/mathjax-26/LICENSE %{buildroot}/usr/share/package-licenses/R-rstudio/dependencies_common_mathjax-26_LICENSE
cp src/cpp/core/json/spirit/LICENSE.txt %{buildroot}/usr/share/package-licenses/R-rstudio/src_cpp_core_json_spirit_LICENSE.txt
cp src/cpp/core/spelling/hunspell/license.hunspell %{buildroot}/usr/share/package-licenses/R-rstudio/src_cpp_core_spelling_hunspell_license.hunspell
cp src/cpp/core/spelling/hunspell/license.myspell %{buildroot}/usr/share/package-licenses/R-rstudio/src_cpp_core_spelling_hunspell_license.myspell
cp src/cpp/session/resources/presentation/revealjs/LICENSE %{buildroot}/usr/share/package-licenses/R-rstudio/src_cpp_session_resources_presentation_revealjs_LICENSE
cp src/cpp/tests/testthat/themes/License.txt %{buildroot}/usr/share/package-licenses/R-rstudio/src_cpp_tests_testthat_themes_License.txt
cp src/gwt/lib/gwt/2.8.1/COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_COPYING
cp src/gwt/lib/gwt/2.8.1/COPYING.html %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_COPYING.html
cp src/gwt/lib/gwt/2.8.1/samples/DynaTable/src/com/google/gwt/sample/dynatable/COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_DynaTable_src_com_google_gwt_sample_dynatable_COPYING
cp src/gwt/lib/gwt/2.8.1/samples/DynaTableRf/src/main/java/com/google/gwt/sample/dynatablerf/COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_DynaTableRf_src_main_java_com_google_gwt_sample_dynatablerf_COPYING
cp src/gwt/lib/gwt/2.8.1/samples/Hello/src/com/google/gwt/sample/hello/COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_Hello_src_com_google_gwt_sample_hello_COPYING
cp src/gwt/lib/gwt/2.8.1/samples/JSON/src/com/google/gwt/sample/json/COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_JSON_src_com_google_gwt_sample_json_COPYING
cp src/gwt/lib/gwt/2.8.1/samples/Mail/src/com/google/gwt/sample/mail/COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_Mail_src_com_google_gwt_sample_mail_COPYING
cp src/gwt/lib/gwt/2.8.1/samples/Validation/src/main/java/com/google/gwt/sample/validation/COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_Validation_src_main_java_com_google_gwt_sample_validation_COPYING
cp src/gwt/src/com/sksamuel/gwt/LICENSE.txt %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_src_com_sksamuel_gwt_LICENSE.txt
cp src/gwt/tools/compiler/COPYING %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_tools_compiler_COPYING
pushd clr-build
%make_install
popd
## install_append content
install -d -m 0755 %{buildroot}/usr/bin
ln -s ../lib64/R/rstudio/bin/rstudio %{buildroot}/usr/bin
cp src/gwt/lib/gin/*/LICENSE %{buildroot}/usr/share/package-licenses/R-rstudio/src_gwt_lib_gin_LICENSE
## install_append end

%files
%defattr(-,root,root,-)
%exclude /usr/lib64/R/rstudio/COPYING
%exclude /usr/lib64/R/rstudio/INSTALL
%exclude /usr/lib64/R/rstudio/NOTICE
%exclude /usr/lib64/R/rstudio/README.md
%exclude /usr/lib64/R/rstudio/SOURCE
%exclude /usr/lib64/R/rstudio/extras/init.d/debian/rstudio-server
%exclude /usr/lib64/R/rstudio/extras/init.d/redhat/rstudio-server
%exclude /usr/lib64/R/rstudio/extras/init.d/suse/rstudio-server
%exclude /usr/lib64/R/rstudio/extras/systemd/rstudio-server.redhat.service
%exclude /usr/lib64/R/rstudio/extras/upstart/rstudio-server.redhat.conf
/usr/lib64/R/rstudio/R/Api.R
/usr/lib64/R/rstudio/R/Diagnostics.R
/usr/lib64/R/rstudio/R/Options.R
/usr/lib64/R/rstudio/R/ServerOptions.R
/usr/lib64/R/rstudio/R/Tools.R
/usr/lib64/R/rstudio/R/modules/ModuleTools.R
/usr/lib64/R/rstudio/R/modules/NotebookAlternateEngines.R
/usr/lib64/R/rstudio/R/modules/NotebookData.R
/usr/lib64/R/rstudio/R/modules/NotebookErrors.R
/usr/lib64/R/rstudio/R/modules/NotebookHtmlWidgets.R
/usr/lib64/R/rstudio/R/modules/NotebookPlots.R
/usr/lib64/R/rstudio/R/modules/SessionAskPass.R
/usr/lib64/R/rstudio/R/modules/SessionAskSecret.R
/usr/lib64/R/rstudio/R/modules/SessionAuthoring.R
/usr/lib64/R/rstudio/R/modules/SessionBreakpoints.R
/usr/lib64/R/rstudio/R/modules/SessionBuild.R
/usr/lib64/R/rstudio/R/modules/SessionClang.R
/usr/lib64/R/rstudio/R/modules/SessionCodeTools.R
/usr/lib64/R/rstudio/R/modules/SessionCompileAttributes.R
/usr/lib64/R/rstudio/R/modules/SessionCompletionHooks.R
/usr/lib64/R/rstudio/R/modules/SessionConnections.R
/usr/lib64/R/rstudio/R/modules/SessionConnectionsInstaller.R
/usr/lib64/R/rstudio/R/modules/SessionConsole.R
/usr/lib64/R/rstudio/R/modules/SessionDataImport.R
/usr/lib64/R/rstudio/R/modules/SessionDataImportV2.R
/usr/lib64/R/rstudio/R/modules/SessionDataPreview.R
/usr/lib64/R/rstudio/R/modules/SessionDataViewer.R
/usr/lib64/R/rstudio/R/modules/SessionDiagnostics.R
/usr/lib64/R/rstudio/R/modules/SessionEnvironment.R
/usr/lib64/R/rstudio/R/modules/SessionErrors.R
/usr/lib64/R/rstudio/R/modules/SessionFiles.R
/usr/lib64/R/rstudio/R/modules/SessionHTMLPreview.R
/usr/lib64/R/rstudio/R/modules/SessionHelp.R
/usr/lib64/R/rstudio/R/modules/SessionJobs.R
/usr/lib64/R/rstudio/R/modules/SessionMarkers.R
/usr/lib64/R/rstudio/R/modules/SessionObjectExplorer.R
/usr/lib64/R/rstudio/R/modules/SessionOverlay.R
/usr/lib64/R/rstudio/R/modules/SessionPackages.R
/usr/lib64/R/rstudio/R/modules/SessionPackrat.R
/usr/lib64/R/rstudio/R/modules/SessionPatches.R
/usr/lib64/R/rstudio/R/modules/SessionPlots.R
/usr/lib64/R/rstudio/R/modules/SessionPlumberViewer.R
/usr/lib64/R/rstudio/R/modules/SessionPresentation.R
/usr/lib64/R/rstudio/R/modules/SessionProfiler.R
/usr/lib64/R/rstudio/R/modules/SessionProjectTemplate.R
/usr/lib64/R/rstudio/R/modules/SessionRAddins.R
/usr/lib64/R/rstudio/R/modules/SessionRCompletions.R
/usr/lib64/R/rstudio/R/modules/SessionRHooks.R
/usr/lib64/R/rstudio/R/modules/SessionRMarkdown.R
/usr/lib64/R/rstudio/R/modules/SessionRSConnect.R
/usr/lib64/R/rstudio/R/modules/SessionRUtil.R
/usr/lib64/R/rstudio/R/modules/SessionReticulate.R
/usr/lib64/R/rstudio/R/modules/SessionRmdNotebook.R
/usr/lib64/R/rstudio/R/modules/SessionShinyViewer.R
/usr/lib64/R/rstudio/R/modules/SessionSource.R
/usr/lib64/R/rstudio/R/modules/SessionSpelling.R
/usr/lib64/R/rstudio/R/modules/SessionSql.R
/usr/lib64/R/rstudio/R/modules/SessionStan.R
/usr/lib64/R/rstudio/R/modules/SessionTests.R
/usr/lib64/R/rstudio/R/modules/SessionThemes.R
/usr/lib64/R/rstudio/R/modules/SessionUpdates.R
/usr/lib64/R/rstudio/R/modules/SessionUserCommands.R
/usr/lib64/R/rstudio/R/modules/SourceWithProgress.R
/usr/lib64/R/rstudio/VERSION
/usr/lib64/R/rstudio/bin/diagnostics
/usr/lib64/R/rstudio/bin/postback/askpass-passthrough
/usr/lib64/R/rstudio/bin/postback/rpostback-askpass
/usr/lib64/R/rstudio/bin/postback/rpostback-editfile
/usr/lib64/R/rstudio/bin/postback/rpostback-gitssh
/usr/lib64/R/rstudio/bin/postback/rpostback-pdfviewer
/usr/lib64/R/rstudio/bin/r-ldpath
/usr/lib64/R/rstudio/bin/rpostback
/usr/lib64/R/rstudio/bin/rserver
/usr/lib64/R/rstudio/bin/rserver-pam
/usr/lib64/R/rstudio/bin/rsession
/usr/lib64/R/rstudio/bin/rstudio
/usr/lib64/R/rstudio/bin/rstudio-backtrace.sh
/usr/lib64/R/rstudio/bin/rstudio-server
/usr/lib64/R/rstudio/extras/pam/rstudio
/usr/lib64/R/rstudio/extras/systemd/rstudio-server.service
/usr/lib64/R/rstudio/extras/themes/README.md
/usr/lib64/R/rstudio/extras/upstart/rstudio-server.conf
/usr/lib64/R/rstudio/resources/CITATION
/usr/lib64/R/rstudio/resources/NOTICE
/usr/lib64/R/rstudio/resources/R.css
/usr/lib64/R/rstudio/resources/connections/actions/help.png
/usr/lib64/R/rstudio/resources/connections/actions/spark-log.png
/usr/lib64/R/rstudio/resources/connections/actions/spark-ui.png
/usr/lib64/R/rstudio/resources/connections/drivers/amazonredshift.png
/usr/lib64/R/rstudio/resources/connections/drivers/amazonredshiftlarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/athena.png
/usr/lib64/R/rstudio/resources/connections/drivers/athenalarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/bigquery.png
/usr/lib64/R/rstudio/resources/connections/drivers/bigquerylarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/cassandra.png
/usr/lib64/R/rstudio/resources/connections/drivers/cassandralarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/couchbase.png
/usr/lib64/R/rstudio/resources/connections/drivers/couchbaselarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/drill.png
/usr/lib64/R/rstudio/resources/connections/drivers/drilllarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/dynamodb.png
/usr/lib64/R/rstudio/resources/connections/drivers/dynamodblarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/hbase.png
/usr/lib64/R/rstudio/resources/connections/drivers/hbaselarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/hive.png
/usr/lib64/R/rstudio/resources/connections/drivers/hivelarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/impala.png
/usr/lib64/R/rstudio/resources/connections/drivers/impalalarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/microsoftsqlserver.png
/usr/lib64/R/rstudio/resources/connections/drivers/microsoftsqlserverlarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/mongodb.png
/usr/lib64/R/rstudio/resources/connections/drivers/mongodblarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/mysql.png
/usr/lib64/R/rstudio/resources/connections/drivers/mysqllarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/netezza.png
/usr/lib64/R/rstudio/resources/connections/drivers/netezzalarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/odbc.png
/usr/lib64/R/rstudio/resources/connections/drivers/oracle.png
/usr/lib64/R/rstudio/resources/connections/drivers/oraclelarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/phoenix.png
/usr/lib64/R/rstudio/resources/connections/drivers/phoenixlarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/postgresql.png
/usr/lib64/R/rstudio/resources/connections/drivers/presto.png
/usr/lib64/R/rstudio/resources/connections/drivers/prestolarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/redshift.png
/usr/lib64/R/rstudio/resources/connections/drivers/redshiftlarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/salesforce.png
/usr/lib64/R/rstudio/resources/connections/drivers/salesforcelarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/spark.png
/usr/lib64/R/rstudio/resources/connections/drivers/sparklarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/sqlite.png
/usr/lib64/R/rstudio/resources/connections/drivers/sqlserver.png
/usr/lib64/R/rstudio/resources/connections/drivers/sqlserverlarge.png
/usr/lib64/R/rstudio/resources/connections/drivers/teradata.png
/usr/lib64/R/rstudio/resources/connections/drivers/teradatalarge.png
/usr/lib64/R/rstudio/resources/connections/objects/catalog.png
/usr/lib64/R/rstudio/resources/connections/objects/database.png
/usr/lib64/R/rstudio/resources/connections/objects/schema.png
/usr/lib64/R/rstudio/resources/connections/objects/table.png
/usr/lib64/R/rstudio/resources/connections/objects/view.png
/usr/lib64/R/rstudio/resources/grid/data-viewer.png
/usr/lib64/R/rstudio/resources/grid/datatables/css/dataTables.scroller.css
/usr/lib64/R/rstudio/resources/grid/datatables/css/dataTables.scroller.min.css
/usr/lib64/R/rstudio/resources/grid/datatables/css/jquery.dataTables.css
/usr/lib64/R/rstudio/resources/grid/datatables/css/jquery.dataTables.min.css
/usr/lib64/R/rstudio/resources/grid/datatables/css/jquery.dataTables_themeroller.css
"/usr/lib64/R/rstudio/resources/grid/datatables/images/Sorting icons.psd"
/usr/lib64/R/rstudio/resources/grid/datatables/images/back_disabled.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/back_enabled.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/back_enabled_hover.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/clear_filter.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/favicon.ico
/usr/lib64/R/rstudio/resources/grid/datatables/images/forward_disabled.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/forward_enabled.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/forward_enabled_hover.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/header_expand.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/loading-background-old.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/sort_asc.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/sort_asc_disabled.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/sort_both.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/sort_desc.png
/usr/lib64/R/rstudio/resources/grid/datatables/images/sort_desc_disabled.png
/usr/lib64/R/rstudio/resources/grid/datatables/js/README
/usr/lib64/R/rstudio/resources/grid/datatables/js/dataTables.scroller.js
/usr/lib64/R/rstudio/resources/grid/datatables/js/dataTables.scroller.min.js
/usr/lib64/R/rstudio/resources/grid/datatables/js/jquery.dataTables.js
/usr/lib64/R/rstudio/resources/grid/datatables/js/jquery.dataTables.min.js
/usr/lib64/R/rstudio/resources/grid/datatables/js/jquery.js
/usr/lib64/R/rstudio/resources/grid/dtstyles.css
/usr/lib64/R/rstudio/resources/grid/dtviewer.js
/usr/lib64/R/rstudio/resources/grid/gridviewer.html
/usr/lib64/R/rstudio/resources/grid/hist.js
/usr/lib64/R/rstudio/resources/grid/object-viewer.png
/usr/lib64/R/rstudio/resources/help_resources/index.htm
/usr/lib64/R/rstudio/resources/help_resources/r-2x.png
/usr/lib64/R/rstudio/resources/help_resources/rstudio-2x.png
/usr/lib64/R/rstudio/resources/help_resources/tip-2x.png
/usr/lib64/R/rstudio/resources/markdown.css
/usr/lib64/R/rstudio/resources/markdown.html
/usr/lib64/R/rstudio/resources/markdown_help.html
/usr/lib64/R/rstudio/resources/mathjax-26/LICENSE
/usr/lib64/R/rstudio/resources/mathjax-26/MathJax.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/AM_CHTML-full.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/AM_CHTML.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/AM_SVG-full.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/AM_SVG.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/MML_CHTML-full.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/MML_CHTML.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/MML_SVG-full.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/MML_SVG.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/MMLorHTML.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/Safe.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-AMS-MML_HTMLorMML.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-AMS_CHTML-full.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-AMS_CHTML.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-AMS_SVG-full.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-AMS_SVG.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-MML-AM_CHTML-full.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-MML-AM_CHTML.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-MML-AM_SVG-full.js
/usr/lib64/R/rstudio/resources/mathjax-26/config/TeX-MML-AM_SVG.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/AssistiveMML.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/CHTML-preview.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/HTML-CSS/handle-floats.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/MatchWebFonts.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/MathEvents.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/MathML/content-mathml.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/MathML/mml3.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/MathZoom.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/Safe.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/AMScd.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/AMSmath.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/AMSsymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/HTML.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/action.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/autobold.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/autoload-all.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/bbox.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/begingroup.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/boldsymbol.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/cancel.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/color.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/enclose.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/extpfeil.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/mathchoice.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/mediawiki-texvc.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/mhchem.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/newcommand.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/noErrors.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/noUndefined.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/unicode.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/TeX/verb.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/asciimath2jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/fast-preview.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/jsMath2jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/mml2jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/tex2jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/extensions/toMathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_AMS-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Caligraphic-Bold.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Caligraphic-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Fraktur-Bold.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Fraktur-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Main-Bold.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Main-Italic.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Main-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Math-BoldItalic.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Math-Italic.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Math-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_SansSerif-Bold.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_SansSerif-Italic.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_SansSerif-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Script-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Size1-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Size2-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Size3-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Size4-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_Typewriter-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_WinChrome-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/otf/MathJax_WinIE6-Regular.otf
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_AMS-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Caligraphic-Bold.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Caligraphic-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Fraktur-Bold.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Fraktur-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Main-Bold.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Main-Italic.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Math-BoldItalic.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Math-Italic.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Math-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_SansSerif-Bold.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_SansSerif-Italic.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_SansSerif-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Script-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Size1-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Size2-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Size3-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Size4-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/fonts/HTML-CSS/TeX/woff/MathJax_Typewriter-Regular.woff
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/Arrows.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/CombDiactForSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/Dingbats.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/GeneralPunctuation.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/GeometricShapes.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/GreekAndCoptic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/Latin1Supplement.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/LetterlikeSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/MathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/MiscMathSymbolsA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/MiscMathSymbolsB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/MiscSymbolsAndArrows.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/MiscTechnical.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/SpacingModLetters.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/SuppMathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/SupplementalArrowsA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/element/mml/optable/SupplementalArrowsB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/AsciiMath/config.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/AsciiMath/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/config.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/a.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/b.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/c.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/d.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/e.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/f.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/fr.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/g.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/h.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/i.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/j.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/k.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/l.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/m.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/n.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/o.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/opf.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/p.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/q.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/r.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/s.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/scr.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/t.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/u.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/v.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/w.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/x.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/y.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/entities/z.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/MathML/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/TeX/config.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/input/TeX/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/autoload/annotation-xml.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/autoload/maction.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/autoload/menclose.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/autoload/mglyph.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/autoload/mmultiscripts.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/autoload/ms.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/autoload/mtable.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/autoload/multiline.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/config.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/AMS-Regular.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/Caligraphic-Bold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/Fraktur-Bold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/Fraktur-Regular.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/Main-Bold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/Math-BoldItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/SansSerif-Bold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/SansSerif-Italic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/SansSerif-Regular.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/Script-Regular.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/Typewriter-Regular.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/fontdata-extra.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/fonts/TeX/fontdata.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/CommonHTML/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/autoload/annotation-xml.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/autoload/maction.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/autoload/menclose.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/autoload/mglyph.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/autoload/mmultiscripts.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/autoload/ms.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/autoload/mtable.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/autoload/multiline.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/config.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/AlphaPresentForms.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/Arrows.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/BBBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/BoldFraktur.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/BoxDrawing.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/CombDiactForSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/ControlPictures.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/CurrencySymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/Cyrillic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/EnclosedAlphanum.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/GeneralPunctuation.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/GeometricShapes.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/GreekAndCoptic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/GreekBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/GreekSSBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/IPAExtensions.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/Latin1Supplement.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/LatinExtendedA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/LatinExtendedAdditional.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/LatinExtendedB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/LatinExtendedD.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/LetterlikeSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/MathBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/MathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/MathSSBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/MiscMathSymbolsA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/MiscMathSymbolsB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/MiscSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/MiscTechnical.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/NumberForms.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/PhoneticExtensions.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/SpacingModLetters.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/SuperAndSubscripts.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Bold/SuppMathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/AlphaPresentForms.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/BoxDrawing.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/CombDiactForSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/ControlPictures.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/CurrencySymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/Cyrillic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/EnclosedAlphanum.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/GeneralPunctuation.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/GreekAndCoptic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/GreekBoldItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/GreekSSBoldItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/IPAExtensions.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/Latin1Supplement.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/LatinExtendedA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/LatinExtendedAdditional.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/LatinExtendedB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/LetterlikeSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/MathBoldItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/MathBoldScript.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/MathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/MathSSItalicBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/BoldItalic/SpacingModLetters.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/AlphaPresentForms.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/BoxDrawing.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/CombDiactForSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/ControlPictures.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/CurrencySymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/Cyrillic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/EnclosedAlphanum.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/GeneralPunctuation.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/GreekAndCoptic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/GreekItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/IPAExtensions.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/Latin1Supplement.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/LatinExtendedA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/LatinExtendedAdditional.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/LatinExtendedB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/LetterlikeSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/MathItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/MathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/MathSSItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/MathScript.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/SpacingModLetters.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Italic/ij.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/AlphaPresentForms.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/Arrows.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/BBBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/BlockElements.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/BoldFraktur.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/BoxDrawing.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/CJK.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/CombDiactForSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/ControlPictures.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/CurrencySymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/Cyrillic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/Dingbats.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/EnclosedAlphanum.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/Fraktur.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/GeneralPunctuation.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/GeometricShapes.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/GreekAndCoptic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/GreekBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/GreekBoldItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/GreekItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/GreekSSBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/GreekSSBoldItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/Hiragana.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/IPAExtensions.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/Latin1Supplement.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/LatinExtendedA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/LatinExtendedAdditional.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/LatinExtendedB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/LatinExtendedD.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/LetterlikeSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathBoldItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathBoldScript.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathSSBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathSSItalic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathSSItalicBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathScript.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MathTT.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MiscMathSymbolsA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MiscMathSymbolsB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MiscSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MiscSymbolsAndArrows.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/MiscTechnical.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/NumberForms.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/PhoneticExtensions.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/SpacingModLetters.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/Specials.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/SuperAndSubscripts.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/SuppMathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/SupplementalArrowsA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/SupplementalArrowsB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/General/Regular/ij.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsD/Bold/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsD/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsD/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsSm/Bold/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsSm/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsSm/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUp/Bold/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUp/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUp/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUpD/Bold/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUpD/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUpD/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUpSm/Bold/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUpSm/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/IntegralsUpSm/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Bold/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Bold/PrivateUse.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/BoldItalic/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/BoldItalic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/BoldItalic/PrivateUse.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Italic/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Italic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Italic/PrivateUse.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/NonUnicode/Regular/PrivateUse.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeFiveSym/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeFiveSym/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeFourSym/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeFourSym/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeFourSym/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeOneSym/Bold/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeOneSym/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeOneSym/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeOneSym/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeThreeSym/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeThreeSym/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeThreeSym/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeTwoSym/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeTwoSym/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/SizeTwoSym/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/Variants/Bold/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/Variants/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/Variants/Regular/All.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/Variants/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/fontdata-1.0.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/fontdata-beta.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/fontdata-extra.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/STIX/fontdata.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/Arrows.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/BBBold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/BoxDrawing.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/Dingbats.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/EnclosedAlphanum.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/GeneralPunctuation.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/GeometricShapes.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/GreekAndCoptic.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/Latin1Supplement.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/LatinExtendedA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/LetterlikeSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/MathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/MiscMathSymbolsB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/MiscSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/MiscTechnical.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/PUA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/SpacingModLetters.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/AMS/Regular/SuppMathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Caligraphic/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Caligraphic/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Fraktur/Bold/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Fraktur/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Fraktur/Bold/Other.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Fraktur/Bold/PUA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Fraktur/Regular/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Fraktur/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Fraktur/Regular/Other.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Fraktur/Regular/PUA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Greek/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Greek/BoldItalic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Greek/Italic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Greek/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/Arrows.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/CombDiactForSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/GeneralPunctuation.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/GeometricShapes.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/Latin1Supplement.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/LatinExtendedA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/LatinExtendedB.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/LetterlikeSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/MathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/MiscMathSymbolsA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/MiscSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/MiscTechnical.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/SpacingModLetters.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/SuppMathOperators.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Bold/SupplementalArrowsA.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Italic/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Italic/GeneralPunctuation.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Italic/Latin1Supplement.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Italic/LetterlikeSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Italic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Regular/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Regular/GeometricShapes.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Regular/MiscSymbols.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Main/Regular/SpacingModLetters.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Math/BoldItalic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Math/Italic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Bold/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Bold/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Bold/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Bold/Other.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Italic/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Italic/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Italic/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Italic/Other.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Regular/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Regular/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/SansSerif/Regular/Other.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Script/Regular/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Script/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Script/Regular/Other.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Size1/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Size2/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Size3/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Size4/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Typewriter/Regular/BasicLatin.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Typewriter/Regular/CombDiacritMarks.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Typewriter/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/Typewriter/Regular/Other.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/WinChrome/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/WinIE6/Regular/AMS.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/WinIE6/Regular/Bold.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/WinIE6/Regular/Main.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/fontdata-extra.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/fonts/TeX/fontdata.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/imageFonts.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/HTML-CSS/jax.js-e
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/NativeMML/config.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/NativeMML/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/PlainSource/config.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/PlainSource/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/PreviewHTML/config.js
/usr/lib64/R/rstudio/resources/mathjax-26/jax/output/PreviewHTML/jax.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ast/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ast/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ast/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ast/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ast/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ast/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ast/ast.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bcc/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bcc/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bcc/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bcc/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bcc/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bcc/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bcc/bcc.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bg/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bg/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bg/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bg/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bg/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bg/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/bg/bg.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/br/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/br/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/br/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/br/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/br/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/br/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/br/br.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ca/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ca/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ca/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ca/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ca/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ca/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ca/ca.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cdo/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cdo/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cdo/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cdo/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cdo/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cdo/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cdo/cdo.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ce/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ce/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ce/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ce/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ce/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ce/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ce/ce.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cs/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cs/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cs/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cs/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cs/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cs/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cs/cs.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cy/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cy/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cy/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cy/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cy/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cy/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/cy/cy.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/da/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/da/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/da/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/da/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/da/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/da/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/da/da.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/de/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/de/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/de/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/de/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/de/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/de/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/de/de.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/en/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/en/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/en/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/en/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/en/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/en/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/en/en.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/eo/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/eo/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/eo/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/eo/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/eo/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/eo/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/eo/eo.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/es/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/es/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/es/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/es/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/es/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/es/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/es/es.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fa/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fa/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fa/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fa/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fa/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fa/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fa/fa.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fi/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fi/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fi/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fi/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fi/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fi/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fi/fi.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fr/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fr/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fr/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fr/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fr/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fr/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/fr/fr.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/gl/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/gl/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/gl/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/gl/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/gl/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/gl/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/gl/gl.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/he/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/he/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/he/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/he/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/he/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/he/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/he/he.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ia/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ia/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ia/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ia/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ia/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ia/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ia/ia.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/it/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/it/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/it/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/it/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/it/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/it/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/it/it.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ja/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ja/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ja/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ja/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ja/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ja/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ja/ja.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/kn/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/kn/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/kn/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/kn/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/kn/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/kn/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/kn/kn.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ko/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ko/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ko/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ko/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ko/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ko/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ko/ko.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lb/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lb/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lb/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lb/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lb/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lb/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lb/lb.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lki/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lki/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lki/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lki/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lki/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lki/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lki/lki.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lt/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lt/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lt/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lt/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lt/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lt/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/lt/lt.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/mk/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/mk/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/mk/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/mk/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/mk/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/mk/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/mk/mk.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/nl/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/nl/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/nl/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/nl/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/nl/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/nl/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/nl/nl.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/oc/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/oc/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/oc/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/oc/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/oc/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/oc/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/oc/oc.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pl/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pl/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pl/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pl/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pl/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pl/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pl/pl.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt-br/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt-br/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt-br/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt-br/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt-br/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt-br/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt-br/pt-br.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/pt/pt.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/qqq/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/qqq/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/qqq/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/qqq/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/qqq/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/qqq/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/qqq/qqq.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ru/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ru/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ru/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ru/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ru/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ru/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/ru/ru.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/scn/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/scn/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/scn/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/scn/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/scn/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/scn/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/scn/scn.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sco/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sco/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sco/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sco/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sco/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sco/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sco/sco.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sl/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sl/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sl/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sl/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sl/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sl/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sl/sl.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sv/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sv/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sv/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sv/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sv/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sv/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/sv/sv.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/tr/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/tr/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/tr/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/tr/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/tr/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/tr/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/tr/tr.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/uk/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/uk/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/uk/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/uk/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/uk/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/uk/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/uk/uk.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/vi/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/vi/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/vi/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/vi/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/vi/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/vi/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/vi/vi.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/zh-hans/FontWarnings.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/zh-hans/HTML-CSS.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/zh-hans/HelpDialog.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/zh-hans/MathML.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/zh-hans/MathMenu.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/zh-hans/TeX.js
/usr/lib64/R/rstudio/resources/mathjax-26/localization/zh-hans/zh-hans.js
/usr/lib64/R/rstudio/resources/mathjax.html
/usr/lib64/R/rstudio/resources/pagedtable/pagedtable.css
/usr/lib64/R/rstudio/resources/pagedtable/pagedtable.js
/usr/lib64/R/rstudio/resources/pandoc_template.html
/usr/lib64/R/rstudio/resources/pdfjs/build/pdf.full.js
/usr/lib64/R/rstudio/resources/pdfjs/build/pdf.js
/usr/lib64/R/rstudio/resources/pdfjs/build/pdf.worker.full.js
/usr/lib64/R/rstudio/resources/pdfjs/build/pdf.worker.js
/usr/lib64/R/rstudio/resources/pdfjs/web/compatibility.full.js
/usr/lib64/R/rstudio/resources/pdfjs/web/compatibility.js
/usr/lib64/R/rstudio/resources/pdfjs/web/debugger.full.js
/usr/lib64/R/rstudio/resources/pdfjs/web/debugger.js
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-check.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-comment.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-help.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-insert.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-key.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-newparagraph.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-noicon.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-note.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/annotation-paragraph.svg
/usr/lib64/R/rstudio/resources/pdfjs/web/images/findbarButton-next-rtl.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/findbarButton-next-rtl_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/findbarButton-next.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/findbarButton-next_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/findbarButton-previous-rtl.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/findbarButton-previous-rtl_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/findbarButton-previous.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/findbarButton-previous_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/loading-small.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/loading-small_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-documentProperties.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-documentProperties_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-firstPage.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-firstPage_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-handTool.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-handTool_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-lastPage.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-lastPage_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-rotateCcw.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-rotateCcw_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-rotateCw.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/secondaryToolbarButton-rotateCw_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/shadow.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/texture.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-bookmark.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-bookmark_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-download.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-download_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-jumpToSource.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-jumpToSource_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-menuArrows.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-menuArrows_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-openFile.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-openFile_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-pageDown-rtl.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-pageDown-rtl_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-pageDown.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-pageDown_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-pageUp-rtl.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-pageUp-rtl_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-pageUp.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-pageUp_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-presentationMode.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-presentationMode_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-print.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-print_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-search.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-search_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-secondaryToolbarToggle-rtl.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-secondaryToolbarToggle-rtl_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-secondaryToolbarToggle.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-secondaryToolbarToggle_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-sidebarToggle-rtl.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-sidebarToggle-rtl_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-sidebarToggle.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-sidebarToggle_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-viewAttachments.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-viewAttachments_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-viewOutline-rtl.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-viewOutline-rtl_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-viewOutline.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-viewOutline_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-viewThumbnail.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-viewThumbnail_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-zoomIn.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-zoomIn_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-zoomOut.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/toolbarButton-zoomOut_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/treeitem-collapsed-rtl.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/treeitem-collapsed-rtl_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/treeitem-collapsed.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/treeitem-collapsed_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/treeitem-expanded.png
/usr/lib64/R/rstudio/resources/pdfjs/web/images/treeitem-expanded_2x.png
/usr/lib64/R/rstudio/resources/pdfjs/web/l10n.full.js
/usr/lib64/R/rstudio/resources/pdfjs/web/l10n.js
/usr/lib64/R/rstudio/resources/pdfjs/web/locale/en-US/viewer.properties
/usr/lib64/R/rstudio/resources/pdfjs/web/locale/locale.properties
/usr/lib64/R/rstudio/resources/pdfjs/web/viewer-rstudio.css
/usr/lib64/R/rstudio/resources/pdfjs/web/viewer.css
/usr/lib64/R/rstudio/resources/pdfjs/web/viewer.css-e
/usr/lib64/R/rstudio/resources/pdfjs/web/viewer.full.js
/usr/lib64/R/rstudio/resources/pdfjs/web/viewer.html
/usr/lib64/R/rstudio/resources/pdfjs/web/viewer.js
/usr/lib64/R/rstudio/resources/plot_publish.html
/usr/lib64/R/rstudio/resources/presentation/helpdoc.css
/usr/lib64/R/rstudio/resources/presentation/helpdoc.html
/usr/lib64/R/rstudio/resources/presentation/mathjax.html
/usr/lib64/R/rstudio/resources/presentation/revealjs/LICENSE
/usr/lib64/R/rstudio/resources/presentation/revealjs/css/print/paper.css
/usr/lib64/R/rstudio/resources/presentation/revealjs/css/print/pdf.css
/usr/lib64/R/rstudio/resources/presentation/revealjs/css/reveal.css
/usr/lib64/R/rstudio/resources/presentation/revealjs/css/reveal.min.css
/usr/lib64/R/rstudio/resources/presentation/revealjs/css/theme/simple.css
/usr/lib64/R/rstudio/resources/presentation/revealjs/fonts/Lato-Bold.ttf
/usr/lib64/R/rstudio/resources/presentation/revealjs/fonts/Lato-BoldItalic.ttf
/usr/lib64/R/rstudio/resources/presentation/revealjs/fonts/Lato-Italic.ttf
/usr/lib64/R/rstudio/resources/presentation/revealjs/fonts/Lato-Regular.ttf
/usr/lib64/R/rstudio/resources/presentation/revealjs/fonts/Lato.css
/usr/lib64/R/rstudio/resources/presentation/revealjs/fonts/NewsCycle-Bold.ttf
/usr/lib64/R/rstudio/resources/presentation/revealjs/fonts/NewsCycle-Regular.ttf
/usr/lib64/R/rstudio/resources/presentation/revealjs/fonts/NewsCycle.css
/usr/lib64/R/rstudio/resources/presentation/revealjs/js/reveal.js
/usr/lib64/R/rstudio/resources/presentation/revealjs/js/reveal.min.js
/usr/lib64/R/rstudio/resources/presentation/revealjs/lib/js/classList.js
/usr/lib64/R/rstudio/resources/presentation/revealjs/lib/js/head.min.js
/usr/lib64/R/rstudio/resources/presentation/revealjs/lib/js/html5shiv.js
/usr/lib64/R/rstudio/resources/presentation/slides-images/correct.png
/usr/lib64/R/rstudio/resources/presentation/slides-images/incorrect.png
/usr/lib64/R/rstudio/resources/presentation/slides.css
/usr/lib64/R/rstudio/resources/presentation/slides.html
/usr/lib64/R/rstudio/resources/presentation/slides.js
/usr/lib64/R/rstudio/resources/profiler/profiler.css
/usr/lib64/R/rstudio/resources/propagate_scroll.js
/usr/lib64/R/rstudio/resources/r_highlight.html
/usr/lib64/R/rstudio/resources/roxygen_help.html
/usr/lib64/R/rstudio/resources/stylesheets/rstudio-gnome-dark.qss
/usr/lib64/R/rstudio/resources/stylesheets/rstudio-gnome-light.qss
/usr/lib64/R/rstudio/resources/stylesheets/rstudio-windows-dark.qss
/usr/lib64/R/rstudio/resources/stylesheets/rstudio-windows-light.qss
/usr/lib64/R/rstudio/resources/templates/.gitignore
/usr/lib64/R/rstudio/resources/templates/ace_theme_template.css
/usr/lib64/R/rstudio/resources/templates/d3.js
/usr/lib64/R/rstudio/resources/templates/plumber/plumber.R
/usr/lib64/R/rstudio/resources/templates/query.sql
/usr/lib64/R/rstudio/resources/templates/r_documentation.Rd
/usr/lib64/R/rstudio/resources/templates/r_documentation_empty.Rd
/usr/lib64/R/rstudio/resources/templates/r_html.Rhtml
/usr/lib64/R/rstudio/resources/templates/r_markdown.Rmd
/usr/lib64/R/rstudio/resources/templates/r_markdown_notebook.Rmd
/usr/lib64/R/rstudio/resources/templates/r_markdown_notebook_osx.Rmd
/usr/lib64/R/rstudio/resources/templates/r_markdown_presentation_shiny.Rmd
/usr/lib64/R/rstudio/resources/templates/r_markdown_shiny.Rmd
/usr/lib64/R/rstudio/resources/templates/r_markdown_v2.Rmd
/usr/lib64/R/rstudio/resources/templates/r_markdown_v2_presentation.Rmd
/usr/lib64/R/rstudio/resources/templates/r_presentation.Rpres
/usr/lib64/R/rstudio/resources/templates/rcpp.cpp
/usr/lib64/R/rstudio/resources/templates/shiny/app.R
/usr/lib64/R/rstudio/resources/templates/shiny/server.R
/usr/lib64/R/rstudio/resources/templates/shiny/ui.R
/usr/lib64/R/rstudio/resources/templates/stan.stan
/usr/lib64/R/rstudio/resources/templates/sweave.Rnw
/usr/lib64/R/rstudio/resources/themes/ambiance.rstheme
/usr/lib64/R/rstudio/resources/themes/chaos.rstheme
/usr/lib64/R/rstudio/resources/themes/chrome.rstheme
/usr/lib64/R/rstudio/resources/themes/clouds.rstheme
/usr/lib64/R/rstudio/resources/themes/clouds_midnight.rstheme
/usr/lib64/R/rstudio/resources/themes/cobalt.rstheme
/usr/lib64/R/rstudio/resources/themes/compile-themes.R
/usr/lib64/R/rstudio/resources/themes/crimson_editor.rstheme
/usr/lib64/R/rstudio/resources/themes/dawn.rstheme
/usr/lib64/R/rstudio/resources/themes/dracula.rstheme
/usr/lib64/R/rstudio/resources/themes/dreamweaver.rstheme
/usr/lib64/R/rstudio/resources/themes/eclipse.rstheme
/usr/lib64/R/rstudio/resources/themes/idle_fingers.rstheme
/usr/lib64/R/rstudio/resources/themes/katzenmilch.rstheme
/usr/lib64/R/rstudio/resources/themes/kr_theme.rstheme
/usr/lib64/R/rstudio/resources/themes/material.rstheme
/usr/lib64/R/rstudio/resources/themes/merbivore.rstheme
/usr/lib64/R/rstudio/resources/themes/merbivore_soft.rstheme
/usr/lib64/R/rstudio/resources/themes/mono_industrial.rstheme
/usr/lib64/R/rstudio/resources/themes/monokai.rstheme
/usr/lib64/R/rstudio/resources/themes/pastel_on_dark.rstheme
/usr/lib64/R/rstudio/resources/themes/solarized_dark.rstheme
/usr/lib64/R/rstudio/resources/themes/solarized_light.rstheme
/usr/lib64/R/rstudio/resources/themes/textmate.rstheme
/usr/lib64/R/rstudio/resources/themes/tomorrow.rstheme
/usr/lib64/R/rstudio/resources/themes/tomorrow_night.rstheme
/usr/lib64/R/rstudio/resources/themes/tomorrow_night_blue.rstheme
/usr/lib64/R/rstudio/resources/themes/tomorrow_night_bright.rstheme
/usr/lib64/R/rstudio/resources/themes/tomorrow_night_eighties.rstheme
/usr/lib64/R/rstudio/resources/themes/twilight.rstheme
/usr/lib64/R/rstudio/resources/themes/vibrant_ink.rstheme
/usr/lib64/R/rstudio/resources/themes/xcode.rstheme
/usr/lib64/R/rstudio/rstudio.png

%files bin
%defattr(-,root,root,-)
/usr/bin/rstudio

%files data
%defattr(-,root,root,-)
/usr/share/applications/rstudio.desktop
/usr/share/icons/hicolor/16x16/apps/rstudio.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-r-data.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-r-project.png
/usr/share/icons/hicolor/24x24/apps/rstudio.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-r-data.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-r-project.png
/usr/share/icons/hicolor/256x256/apps/rstudio.png
/usr/share/icons/hicolor/256x256/mimetypes/application-x-r-data.png
/usr/share/icons/hicolor/256x256/mimetypes/application-x-r-project.png
/usr/share/icons/hicolor/32x32/apps/rstudio.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-r-data.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-r-project.png
/usr/share/icons/hicolor/48x48/apps/rstudio.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-r-data.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-r-project.png
/usr/share/mime-packages/rstudio.xml
/usr/share/pixmaps/rstudio.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-rstudio/COPYING
/usr/share/package-licenses/R-rstudio/NOTICE
/usr/share/package-licenses/R-rstudio/dependencies_common_mathjax-26_LICENSE
/usr/share/package-licenses/R-rstudio/src_cpp_core_json_spirit_LICENSE.txt
/usr/share/package-licenses/R-rstudio/src_cpp_core_spelling_hunspell_license.hunspell
/usr/share/package-licenses/R-rstudio/src_cpp_core_spelling_hunspell_license.myspell
/usr/share/package-licenses/R-rstudio/src_cpp_session_resources_presentation_revealjs_LICENSE
/usr/share/package-licenses/R-rstudio/src_cpp_tests_testthat_themes_License.txt
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gin_LICENSE
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_COPYING
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_COPYING.html
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_DynaTableRf_src_main_java_com_google_gwt_sample_dynatablerf_COPYING
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_DynaTable_src_com_google_gwt_sample_dynatable_COPYING
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_Hello_src_com_google_gwt_sample_hello_COPYING
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_JSON_src_com_google_gwt_sample_json_COPYING
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_Mail_src_com_google_gwt_sample_mail_COPYING
/usr/share/package-licenses/R-rstudio/src_gwt_lib_gwt_2.8.1_samples_Validation_src_main_java_com_google_gwt_sample_validation_COPYING
/usr/share/package-licenses/R-rstudio/src_gwt_src_com_sksamuel_gwt_LICENSE.txt
/usr/share/package-licenses/R-rstudio/src_gwt_tools_compiler_COPYING
